title: "Ракурс"
baseurl: "/rakurs-news.github.io"
url: "https://rakurs-news.github.io"

markdown: kramdown
theme: minima

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
