name: Генерация новостей

on:
  schedule:
    - cron: '0 0 * * *' # запуск каждый день в полночь
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Установка зависимостей
        run: npm install
      - name: Генерация новостей
        run: node generateNews.js
      - name: Коммит и пуш изменений
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/news.html
          git commit -m "Автообновление новостей"
          git push
