name: Deploy Site

on:
  push:
    branches:
      - main  # или ваша ветка, на которую пушите новости

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Можно добавить шаги по сборке, если используете генератор статик-сайтов, например, Jekyll, Hugo, или VuePress
    # В вашем случае, если сайт статичный без сборки, пропускаем этот шаг

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # ветка, куда будет деплоиться сайт
        folder: ./  # папка, где находится сайт (скорее всего, корень проекта)
